### ISSUE TITLE
White text on white background in input boxes for anki, 

### ISSUE THREAD

**Issue by dnecklesportfolio** [krassowski/Anki-Night-Mode#84] opened 2019-09-23 03:06 UTC
#### Problem description
When the option "Enable in dialogs" is ticked, and say if i change a tag... the color of the text is white but the background is also white, it should be black. See attached.
![Screen Shot 2019-09-22 at 11 03 09 PM](https://user-images.githubusercontent.com/2013689/65399944-6f5cf100-dd8d-11e9-9c40-ab9b3ebb4f87.png)

*Describe problem concisely in here*

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [ x] I verified that I use the lastest add-on version,
 - [x ] I verified that I use the lastest Anki version,
 - [ ] I tried to disable other add-ons to find the culprit,
 - [x ] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [ ] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*

```
Version:
Qt:
```

*Please got to Night Mode → About now and copy-paste the first line from the pop-up window below:*

```
Night Mode x.x.x
```

*Please fill in your OS details (Linux/Mac/Windows):*

```
OS:
```
 
 
*If you have a compatibility problem with a specific add-on or add-ons, please paste the add-on page links below:*
 - [Other add-on name](https://)
</details>

#### Backtrace (if any)

<details>

*If you had an error which resulted in producing exception with a backtrace, please paste the backtrace below:*

```python"
[paste your backtrace in here if you got any; otherwise feel free to remove this part]
```

</details>

**Comment by krassowski** [comment] 2019-09-23 09:31
Duplicate of #59.

**Closed by krassowski** 2019-09-23 09:31 UTC
