### ISSUE TITLE
Tag text is too light to read

### ISSUE THREAD

**Issue by Z1839** [krassowski/Anki-Night-Mode#74] opened 2019-06-05 14:06 UTC
I've been having issues with adding tags with night mode. Whenever I try to add tags during review, and from the browser, the text is very, very light grey and difficult to read.

If you could look into this issue it would be very appreciated. Thank you.

**Comment by sereneavatar** [comment] 2019-06-09 20:31
> I've been having issues with adding tags with night mode. Whenever I try to add tags during review, and from the browser, the text is very, very light grey and difficult to read.
> 
> If you could look into this issue it would be very appreciated. Thank you.

Yes, I'm experiencing the same problem (on macOS High Sierra) and from what I could gather it seems to be that

```
@css
    def completer(self):
        return """
            background-color:black;
            border-color:#444;
            color:#eee;
        """
```

in **stylers.py** only overrides the text color, but not the background color (except in the completer popup), so if want a temporary fix you could change the css to something like

```
@css
    def completer(self):
        return """
            background-color:#fff;
            border-color:#444;
            color:#000;
        """
```

until the editor styling gets updated 🙂

**Comment by Z1839** [comment] 2019-06-10 12:56
Ah, I appreciate the input.

Perhaps you should bring this up with the anki devs

**Comment by Z1839** [comment] 2019-06-20 20:01
Just an update: I still can't see tag text in the browser when I try to add tags. The text is essentially white on a white background. Any idea my friend?

**Comment by krassowski** [comment] 2019-08-05 15:39
Closing as a duplicate of #59. If this is wrong, please re-open pointing out the differences between the two issues.

**Closed by krassowski** 2019-08-05 15:39 UTC
Labels: macOS
